// D&D 3.5e Progression Tables and Logic
window.DND_PROGRESSION = {
    // Mathematical formulas for base stats
    calcBAB: function(level, type) {
        if (type === 'good') return Math.floor(level * 1.0);
        if (type === 'average') return Math.floor(level * 0.75);
        if (type === 'poor') return Math.floor(level * 0.5);
        return 0;
    },
    calcSave: function(level, type) {
        if (type === 'good') return Math.floor(level / 2) + 2;
        if (type === 'poor') return Math.floor(level / 3);
        return 0;
    },

    // Class Features per level
    classFeatures: {
        "barbarian": {
            1: ["Movimiento rápido", "Furia 1/día"],
            2: ["Esquiva asombrosa"],
            3: ["Sentido de las trampas +1"],
            4: ["Furia 2/día"],
            5: ["Esquiva asombrosa mejorada"],
            6: ["Sentido de las trampas +2"],
            7: ["Reducción de daño 1/-"],
            8: ["Furia 3/día"],
            9: ["Sentido de las trampas +3"],
            10: ["Reducción de daño 2/-"],
            11: ["Furia mayor", "Furia 4/día"],
            12: ["Sentido de las trampas +4"],
            13: ["Reducción de daño 3/-"],
            14: ["Voluntad indomable"],
            15: ["Sentido de las trampas +5"],
            16: ["Reducción de daño 4/-", "Furia 5/día"],
            17: ["Furia incansable"],
            18: ["Sentido de las trampas +6"],
            19: ["Reducción de daño 5/-"],
            20: ["Furia poderosa", "Furia 6/día"]
        },
        "bard": {
            1: ["Música de bardo", "Conocimiento de bardo", "Infundir valor +1", "Fascinar", "Cántico de victoria"],
            2: ["-"],
            3: ["Infundir entereza"],
            4: ["-"],
            5: ["-"],
            6: ["Sugestión"],
            7: ["-"],
            8: ["Infundir valor +2"],
            9: ["Infundir grandeza"],
            10: ["-"],
            11: ["-"],
            12: ["Canto de libertad"],
            13: ["-"],
            14: ["Infundir valor +3"],
            15: ["Infundir heroicidad"],
            16: ["-"],
            17: ["-"],
            18: ["Sugestión en masa"],
            19: ["-"],
            20: ["Infundir valor +4"]
        },
        "cleric": {
            1: ["Expulsar o reprender muertos vivientes", "Dominios"],
            2: ["-"], 3: ["-"], 4: ["-"], 5: ["-"], 6: ["-"], 7: ["-"], 8: ["-"], 9: ["-"], 10: ["-"],
            11: ["-"], 12: ["-"], 13: ["-"], 14: ["-"], 15: ["-"], 16: ["-"], 17: ["-"], 18: ["-"], 19: ["-"], 20: ["-"]
        },
        "druid": {
            1: ["Compañero animal", "Vínculo con la naturaleza", "Sentido de la naturaleza", "Empatía salvaje"],
            2: ["Pisada sin rastro"],
            3: ["Zancada forestal"],
            4: ["Resistir la tentación de la naturaleza"],
            5: ["Forma salvaje (1/día)"],
            6: ["Forma salvaje (2/día)"],
            7: ["Forma salvaje (3/día)"],
            8: ["Forma salvaje (G/M)"],
            9: ["Inmunidad al veneno"],
            10: ["Forma salvaje (4/día)"],
            11: ["Forma salvaje (Dimen)"],
            12: ["Forma salvaje (Planta)"],
            13: ["A las mil caras"],
            14: ["Forma salvaje (5/día)"],
            15: ["Cuerpo atemporal", "Forma salvaje (Enorme)"],
            16: ["Forma salvaje (Elemental 1/día)"],
            17: ["-"],
            18: ["Forma salvaje (6/día)", "Forma salvaje (Elemental 2/día)"],
            19: ["-"],
            20: ["Forma salvaje (Elemental 3/día)"]
        },
        "fighter": {
            1: ["Dote suplementaria"],
            2: ["Dote suplementaria"],
            3: ["-"],
            4: ["Dote suplementaria"],
            5: ["-"],
            6: ["Dote suplementaria"],
            7: ["-"],
            8: ["Dote suplementaria"],
            9: ["-"],
            10: ["Dote suplementaria"],
            11: ["-"],
            12: ["Dote suplementaria"],
            13: ["-"],
            14: ["Dote suplementaria"],
            15: ["-"],
            16: ["Dote suplementaria"],
            17: ["-"],
            18: ["Dote suplementaria"],
            19: ["-"],
            20: ["Dote suplementaria"]
        },
        "monk": {
            1: ["Impacto sin arma", "Ráfaga de golpes", "Dote suplementaria", "CA adicional"],
            2: ["Dote suplementaria", "Evasión"],
            3: ["Mente en calma", "Movimiento rápido"],
            4: ["Impacto ki (mágico)", "Caída lenta 20'"],
            5: ["Pureza corporal"],
            6: ["Dote suplementaria", "Caída lenta 30'"],
            7: ["Plenitud corporal"],
            8: ["Caída lenta 40'"],
            9: ["Evasión mejorada"],
            10: ["Impacto ki (legal)", "Caída lenta 50'"],
            11: ["Cuerpo diamantino", "Ráfaga mayor"],
            12: ["Paso abundante", "Caída lenta 60'"],
            13: ["Alma diamantina"],
            14: ["Caída lenta 70'"],
            15: ["Palma temblorosa"],
            16: ["Impacto ki (adamantino)", "Caída lenta 80'"],
            17: ["Cuerpo atemporal", "Lengua del sol y la luna"],
            18: ["Caída lenta 90'"],
            19: ["Cuerpo vacío"],
            20: ["Perfección perfecta", "Caída lenta cualquier distancia"]
        },
        "paladin": {
            1: ["Aura de bien", "Detectar el mal", "Castigar al mal 1/día"],
            2: ["Gracia divina", "Imposición de manos"],
            3: ["Aura de valor", "Salud divina"],
            4: ["Expulsar muertos vivientes"],
            5: ["Castigar al mal 2/día", "Montura especial"],
            6: ["Quitar enfermedad 1/semana"],
            7: ["-"],
            8: ["-"],
            9: ["Quitar enfermedad 2/semana"],
            10: ["Castigar al mal 3/día"],
            11: ["-"],
            12: ["Quitar enfermedad 3/semana"],
            13: ["-"],
            14: ["-"],
            15: ["Quitar enfermedad 4/semana", "Castigar al mal 4/día"],
            16: ["-"],
            17: ["-"],
            18: ["Quitar enfermedad 5/semana"],
            19: ["-"],
            20: ["Castigar al mal 5/día"]
        },
        "ranger": {
            1: ["1º Enemigo predilecto", "Rastrear", "Empatía salvaje"],
            2: ["Estilo de combate"],
            3: ["Aguante"],
            4: ["Compañero animal"],
            5: ["2º Enemigo predilecto"],
            6: ["Estilo de combate mejorado"],
            7: ["Zancada forestal"],
            8: ["Rastreador veloz"],
            9: ["Evasión"],
            10: ["3º Enemigo predilecto"],
            11: ["Dominio del estilo de combate"],
            12: ["-"],
            13: ["Camuflaje"],
            14: ["-"],
            15: ["4º Enemigo predilecto"],
            16: ["-"],
            17: ["Esconderse a simple vista"],
            18: ["-"],
            19: ["-"],
            20: ["5º Enemigo predilecto"]
        },
        "rogue": {
            1: ["Ataque furtivo +1d6", "Encontrar trampas"],
            2: ["Evasión"],
            3: ["Ataque furtivo +2d6", "Sentido de las trampas +1"],
            4: ["Esquiva asombrosa"],
            5: ["Ataque furtivo +3d6"],
            6: ["Sentido de las trampas +2"],
            7: ["Ataque furtivo +4d6"],
            8: ["Esquiva asombrosa mejorada"],
            9: ["Ataque furtivo +5d6", "Sentido de las trampas +3"],
            10: ["Capacidad especial"],
            11: ["Ataque furtivo +6d6"],
            12: ["Sentido de las trampas +4"],
            13: ["Ataque furtivo +7d6", "Capacidad especial"],
            14: ["-"],
            15: ["Ataque furtivo +8d6", "Sentido de las trampas +5"],
            16: ["Capacidad especial"],
            17: ["Ataque furtivo +9d6"],
            18: ["Sentido de las trampas +6"],
            19: ["Ataque furtivo +10d6", "Capacidad especial"],
            20: ["-"]
        },
        "sorcerer": {
            1: ["Invocar familiar"],
            2: ["-"], 3: ["-"], 4: ["-"], 5: ["-"], 6: ["-"], 7: ["-"], 8: ["-"], 9: ["-"], 10: ["-"],
            11: ["-"], 12: ["-"], 13: ["-"], 14: ["-"], 15: ["-"], 16: ["-"], 17: ["-"], 18: ["-"], 19: ["-"], 20: ["-"]
        },
        "wizard": {
            1: ["Invocar familiar", "Scribir rollo"],
            2: ["-"], 3: ["-"], 4: ["-"], 
            5: ["Dote suplementaria"], 
            6: ["-"], 7: ["-"], 8: ["-"], 9: ["-"], 
            10: ["Dote suplementaria"],
            11: ["-"], 12: ["-"], 13: ["-"], 14: ["-"], 
            15: ["Dote suplementaria"],
            16: ["-"], 17: ["-"], 18: ["-"], 19: ["-"], 
            20: ["Dote suplementaria"]
        }
    }
};
